// <auto-generated />
using System;
using Car.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Car.Api.Migrations
{
    [DbContext(typeof(CarContext))]
    partial class CarContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Car.Entities.Concrete.CompanyPerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("CompanyPersons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2021, 4, 16, 2, 33, 21, 453, DateTimeKind.Local).AddTicks(8902),
                            Email = "admin@admin.com",
                            IsActive = true,
                            ModifiedDate = new DateTime(2021, 4, 16, 2, 33, 21, 453, DateTimeKind.Local).AddTicks(8934),
                            Name = "Admin",
                            Password = "$2a$11$ns/Lu/fYbT1V1xO1uQe8YedejQ87i2E2G.QosnG57JiFqo9VDcA1e"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2021, 4, 16, 2, 33, 21, 659, DateTimeKind.Local).AddTicks(8629),
                            Email = "super@super.com",
                            IsActive = true,
                            ModifiedDate = new DateTime(2021, 4, 16, 2, 33, 21, 659, DateTimeKind.Local).AddTicks(8660),
                            Name = "SuperAdmin",
                            Password = "$2a$11$ItzpzlvG0DF8PB7CMnM4MehUtM45Xbjsu5RJ8Z1/HAZIWvZr3a0jm"
                        });
                });

            modelBuilder.Entity("Car.Entities.Concrete.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TaxNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adress = "Düzce/Akçakoca",
                            CreatedDate = new DateTime(2021, 4, 16, 2, 33, 21, 233, DateTimeKind.Local).AddTicks(7409),
                            Email = "test@test.com",
                            IsActive = true,
                            ModifiedDate = new DateTime(2021, 4, 16, 2, 33, 21, 235, DateTimeKind.Local).AddTicks(1196),
                            Name = "test",
                            PhoneNumber = "0533423424",
                            TaxNo = "123456"
                        },
                        new
                        {
                            Id = 2,
                            Adress = "Düzce/Merkez",
                            CreatedDate = new DateTime(2021, 4, 16, 2, 33, 21, 235, DateTimeKind.Local).AddTicks(1809),
                            Email = "test2@test.com",
                            IsActive = true,
                            ModifiedDate = new DateTime(2021, 4, 16, 2, 33, 21, 235, DateTimeKind.Local).AddTicks(1816),
                            Name = "test2",
                            PhoneNumber = "0539851524",
                            TaxNo = "654321"
                        },
                        new
                        {
                            Id = 3,
                            Adress = "Zonguldak/Merkez",
                            CreatedDate = new DateTime(2021, 4, 16, 2, 33, 21, 235, DateTimeKind.Local).AddTicks(1819),
                            Email = "test3@test.com",
                            IsActive = true,
                            ModifiedDate = new DateTime(2021, 4, 16, 2, 33, 21, 235, DateTimeKind.Local).AddTicks(1820),
                            Name = "test3",
                            PhoneNumber = "0539851524",
                            TaxNo = "232424"
                        },
                        new
                        {
                            Id = 4,
                            Adress = "Bolu/Merkez",
                            CreatedDate = new DateTime(2021, 4, 16, 2, 33, 21, 235, DateTimeKind.Local).AddTicks(1822),
                            Email = "test4@test.com",
                            IsActive = true,
                            ModifiedDate = new DateTime(2021, 4, 16, 2, 33, 21, 235, DateTimeKind.Local).AddTicks(1823),
                            Name = "test4",
                            PhoneNumber = "0554551524",
                            TaxNo = "6543656"
                        });
                });

            modelBuilder.Entity("Car.Entities.Concrete.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyPersonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payment")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyPersonId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Car.Entities.Concrete.InvoiceProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VehiclePartId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("VehiclePartId");

                    b.ToTable("InvoiceProducts");
                });

            modelBuilder.Entity("Car.Entities.Concrete.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Ford",
                            CreatedDate = new DateTime(2021, 4, 16, 2, 33, 21, 239, DateTimeKind.Local).AddTicks(2165),
                            IsActive = true,
                            Model = "Focus",
                            ModifiedDate = new DateTime(2021, 4, 16, 2, 33, 21, 239, DateTimeKind.Local).AddTicks(1019)
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Volvo",
                            CreatedDate = new DateTime(2021, 4, 16, 2, 33, 21, 239, DateTimeKind.Local).AddTicks(2175),
                            IsActive = true,
                            Model = "S60",
                            ModifiedDate = new DateTime(2021, 4, 16, 2, 33, 21, 239, DateTimeKind.Local).AddTicks(2173)
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Audi",
                            CreatedDate = new DateTime(2021, 4, 16, 2, 33, 21, 239, DateTimeKind.Local).AddTicks(2178),
                            IsActive = true,
                            Model = "Quadrado",
                            ModifiedDate = new DateTime(2021, 4, 16, 2, 33, 21, 239, DateTimeKind.Local).AddTicks(2176)
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Tofaş",
                            CreatedDate = new DateTime(2021, 4, 16, 2, 33, 21, 239, DateTimeKind.Local).AddTicks(2180),
                            IsActive = true,
                            Model = "Şahin",
                            ModifiedDate = new DateTime(2021, 4, 16, 2, 33, 21, 239, DateTimeKind.Local).AddTicks(2179)
                        });
                });

            modelBuilder.Entity("Car.Entities.Concrete.VehiclePart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("BuyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PartCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PartType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("SellPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TaxStatus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleParts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuyPrice = 300m,
                            CreatedDate = new DateTime(2021, 4, 16, 2, 33, 21, 241, DateTimeKind.Local).AddTicks(9140),
                            IsActive = true,
                            ModifiedDate = new DateTime(2021, 4, 16, 2, 33, 21, 241, DateTimeKind.Local).AddTicks(9159),
                            PartCode = "A81",
                            PartType = "Akü",
                            SellPrice = 400m,
                            Stock = 50,
                            TaxRate = 18m,
                            TaxStatus = "Yüksek",
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 2,
                            BuyPrice = 700m,
                            CreatedDate = new DateTime(2021, 4, 16, 2, 33, 21, 242, DateTimeKind.Local).AddTicks(3302),
                            IsActive = true,
                            ModifiedDate = new DateTime(2021, 4, 16, 2, 33, 21, 242, DateTimeKind.Local).AddTicks(3310),
                            PartCode = "C54",
                            PartType = "Cam",
                            SellPrice = 850m,
                            Stock = 1000,
                            TaxRate = 15m,
                            TaxStatus = "Orta",
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 3,
                            BuyPrice = 200m,
                            CreatedDate = new DateTime(2021, 4, 16, 2, 33, 21, 242, DateTimeKind.Local).AddTicks(3314),
                            IsActive = true,
                            ModifiedDate = new DateTime(2021, 4, 16, 2, 33, 21, 242, DateTimeKind.Local).AddTicks(3316),
                            PartCode = "J34",
                            PartType = "Jant",
                            SellPrice = 400m,
                            Stock = 1000,
                            TaxRate = 25m,
                            TaxStatus = "Yüksek",
                            VehicleId = 3
                        },
                        new
                        {
                            Id = 4,
                            BuyPrice = 50m,
                            CreatedDate = new DateTime(2021, 4, 16, 2, 33, 21, 242, DateTimeKind.Local).AddTicks(3318),
                            IsActive = true,
                            ModifiedDate = new DateTime(2021, 4, 16, 2, 33, 21, 242, DateTimeKind.Local).AddTicks(3320),
                            PartCode = "S11",
                            PartType = "Silecek",
                            SellPrice = 65m,
                            Stock = 1000,
                            TaxRate = 10m,
                            TaxStatus = "Yüksek",
                            VehicleId = 2
                        });
                });

            modelBuilder.Entity("Car.Entities.Concrete.Invoice", b =>
                {
                    b.HasOne("Car.Entities.Concrete.CompanyPerson", "CompanyPerson")
                        .WithMany()
                        .HasForeignKey("CompanyPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Car.Entities.Concrete.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyPerson");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Car.Entities.Concrete.InvoiceProduct", b =>
                {
                    b.HasOne("Car.Entities.Concrete.Invoice", "Invoice")
                        .WithMany("InvoiceProducts")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Car.Entities.Concrete.VehiclePart", "VehiclePart")
                        .WithMany()
                        .HasForeignKey("VehiclePartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("VehiclePart");
                });

            modelBuilder.Entity("Car.Entities.Concrete.VehiclePart", b =>
                {
                    b.HasOne("Car.Entities.Concrete.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Car.Entities.Concrete.Invoice", b =>
                {
                    b.Navigation("InvoiceProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
